feat: add k8s_namespace() to pull cached namespace
tilt-dev/tilt pull request #5935
Opened 2022-09-09 20:04 UTC by nsheaps

2022-09-09 20:20 UTC, kylelemons requested changes

2022-09-09 20:20 UTC, kylelemons commented on internal/tiltfile/tiltfile_test.go
> -	k8sContextPlugin := k8scontext.NewPlugin(f.k8sContext, f.k8sEnv)
missing test coverage, see:
https://sourcegraph.com/github.com/tilt-dev/tilt/-/blob/internal/tiltfile/tiltfile_test.go?L3601:4

2022-09-12 14:29 UTC, nsheaps commented on internal/tiltfile/tiltfile_test.go
> -	k8sContextPlugin := k8scontext.NewPlugin(f.k8sContext, f.k8sEnv)
Fixed

2022-09-12 19:33 UTC, nicks commented
lgtm, but the build is failing because you need to run `gofmt` or `goimports`?

2022-09-12 20:53 UTC, kylelemons approved these changes

2022-09-12 21:02 UTC, nicks approved these changes
LGTM! thanks!

2022-09-12 21:02 UTC, merged